---
version: 1

# build_arg_defaults:
  # EE_BASE_IMAGE: "registry.redhat.io/ansible-automation-platform-21/ee-supported-rhel8:1.0.0-6"
  # EE_BUILDER_IMAGE: "registry.redhat.io/ansible-automation-platform-21/ansible-builder-rhel8:1.0.1-4"

ansible_config: "ansible.cfg"

dependencies:
  galaxy: requirements.yml
  python: requirements.txt

additional_build_steps:
  prepend: |
    # Install the Azure CLI
    RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc
    RUN dnf install -y https://packages.microsoft.com/config/rhel/8/packages-microsoft-prod.rpm
    RUN echo -e "[azure-cli] \
        name=Azure CLI \
        baseurl=https://packages.microsoft.com/yumrepos/azure-cli \
        enabled=1 \
        gpgcheck=1 \
        gpgkey=https://packages.microsoft.com/keys/microsoft.asc" | tee /etc/yum.repos.d/azure-cli.repo
    RUN dnf install -y unzip azure-cli

    # Install the Azure Connected Machine Extension
    RUN az config set extension.use_dynamic_install=yes_without_prompt
    RUN az extension add --name connectedmachine -y

    # Install the Terraform CLI
    RUN dnf config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    RUN dnf install terraform -y
    
  append: |
    # Install OCI CLI
    RUN curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh -o install.sh
    RUN chmod 755 install.sh
    RUN ./install.sh --accept-all-defaults
    RUN rm install.sh

    # Install the gcloud CLI
    RUN if [ $TARGETARCH == "arm64" ]; then curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-410.0.0-linux-arm.tar.gz; else curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-410.0.0-linux-x86_64.tar.gz; fi
    RUN if [ $TARGETARCH == "arm64" ]; then tar -xf google-cloud-cli-410.0.0-linux-arm.tar.gz; else tar -xf google-cloud-cli-410.0.0-linux-x86_64.tar.gz; fi
    RUN ./google-cloud-sdk/install.sh -q --usage-reporting false
    RUN if [ $TARGETARCH == "arm64" ]; then rm google-cloud-cli-410.0.0-linux-arm.tar.gz; else rm google-cloud-cli-410.0.0-linux-x86_64.tar.gz; fi

    # Install AWS CLI
    RUN if [ $TARGETARCH == "arm64" ]; then curl -O https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip; else curl -O https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip; fi
    RUN if [ $TARGETARCH == "arm64" ]; then unzip awscli-exe-linux-aarch64.zip; else unzip awscli-exe-linux-x86_64.zip; fi
    RUN ./aws/install
    RUN if [ $TARGETARCH == "arm64" ]; then rm awscli-exe-linux-aarch64.zip; else rm awscli-exe-linux-x86_64.zip; fi

    # Extra Steps
    RUN echo "export PATH=/home/runner/lib/oracle-cli/bin/:/runner/google-cloud-sdk/bin/:$PATH" >> /home/runner/.bashrc
    RUN source /home/runner/.bashrc
