---
collections:
  - name: amazon.aws
    version: 4.0.0
  - name: ansible.windows
  - name: azure.azcollection
    version: 1.13.0
  - name: awx.awx
    version: 21.2.0
  - name: community.aws
    version: 4.0.0
  - name: community.general
    version: 5.5.0
  - name: https://github.com/ansible-collections/amazon.cloud.git
    version: 0.1.0
    type: git
  - name: oracle.oci
    version: 3.0.1
  - name: https://github.com/ansible-content-lab/azure.infrastructure_config_demos.git
    version: main
    type: git
  - name: https://github.com/ansible-content-lab/aws.infrastructure_config_demos.git
    version: main
    type: git
  - name: https://github.com/ansible-content-lab/aoc.controller_demo_config.git
    version: main
    type: git
