---
collections:
  - name: amazon.aws
    version: 5.0.0
  - name: https://github.com/ansible-collections/amazon.cloud.git
    version: 0.2.0
    type: git
  - name: azure.azcollection
    version: 1.14.0
  - name: ansible.windows
  - name: awx.awx
    version: 21.8.0
  - name: cloud.terraform
    version: 1.0.0
  - name: community.aws
    version: 5.0.0
  - name: community.general
    version: 6.1.0
  - name: oracle.oci
    version: 4.4.0
  - name: google.cloud
    version: 1.0.2
