---
collections:
  - name: amazon.aws
    version: 5.0.2
  - name: ansible.windows
  - name: azure.azcollection
    version: 1.14.0
  - name: awx.awx
    version: 21.8.0
  - name: community.aws
    version: 5.0.0
  - name: community.general
    version: 5.8.0
  - name: https://github.com/ansible-collections/amazon.cloud.git
    version: 0.2.0
    type: git
  - name: oracle.oci
    version: 3.5.0
  - name: google.cloud
    version: 1.0.2
  - name: https://github.com/ansible-content-lab/azure.infrastructure_config_demos.git
    version: main
    type: git
  - name: https://github.com/ansible-content-lab/aws.infrastructure_config_demos.git
    version: main
    type: git
  - name: https://github.com/ansible-content-lab/aoc.controller_demo_config.git
    version: main
    type: git
