---
collections:
  - name: amazon.aws
    version: 3.3.0
  - name: azure.azcollection
    version: 1.13.0
  - name: awx.awx
    version: 21.1.0
  - name: community.aws
    version: 3.3.0
  - name: https://github.com/ansible-collections/amazon.cloud.git
    version: 0.1.0
    type: git
roles:
  - name: cloud.azure_roles
    scm: git
    src: https://github.com/ansible-collections/cloud.azure_roles.git
    version: main
  - name: ansible_on_clouds.aoc_demo_setup
    scm: git
    src: https://github.com/scottharwell/aoc_demo_setup.git
    version: main
