---
collections:
  - name: amazon.aws
    version: 4.0.0
  - name: azure.azcollection
    version: 1.13.0
  - name: awx.awx
    version: 21.2.0
  - name: community.aws
    version: 4.0.0
  - name: https://github.com/ansible-collections/amazon.cloud.git
    version: 0.1.0
    type: git
  - name: oracle.oci
    version: 2.53.0
  - name: https://github.com/ansible-collections/cloud.azure_roles.git
    version: main
    type: git
  - name: https://github.com/ansible-content-lab/cloud.aws_roles.git
    version: main
    type: git
roles:
  - name: ansible_on_clouds.aoc_demo_setup
    src: https://github.com/scottharwell/aoc_demo_setup.git
    version: main
